views:
  - title: Home
    cards:
      - show_header_toggle: true
        type: entities
        title: People
        entities:
          - device_tracker.samsung_s8
          - device_tracker.samsung_s8_bt
          - device_tracker.samsung_gear_s2
          - device_tracker.samsung_gear_s2_bt
          - sensor.guy_presence
          - sensor.meital_presence
      - show_header_toggle: true
        type: entities
        title: Entryway
        entities:
          - switch.sonoff_10004bd3c1
      - type: media-control
        entity: media_player.entryway_speaker
      - show_header_toggle: true
        type: entities
        title: Living Room
        entities:
          - light.xiaomi_philips_smart_led_ball
      - type: media-control
        entity: media_player.kodi
      - type: media-control
        entity: media_player.samsung_tv_remote
      - type: media-control
        entity: media_player.living_room_tv
      - type: picture-entity
        entity: camera.foscam_mjpeg
      - type: picture-entity
        entity: camera.foscam_native
      - type: 'custom:weather-card'
        entity: weather.dark_sky
      - show_header_toggle: false
        type: entities
        title: Robot Vacuum
        entities:
          - vacuum.xiaomi_vacuum_cleaner
      - show_header_toggle: false
        type: entities
        title: Vacuum a Room
        entities:
          - input_select.vacuum_room
          - binary_sensor.vacuum_room
      - entity: light.xiaomi_philips_smart_led_ball
        type: light
        theme: Backend-selected
        name: Xiaomi Philips Smart Led
    badges: []
    path: default_view
  - title: System
    cards:
      - show_header_toggle: true
        type: entities
        title: System Status
        entities:
          - entity: sensor.date
          - entity: sensor.time
          - entity: sensor.last_boot
          - entity: sensor.ha_installed_version
          - entity: updater.updater
          - entity: sensor.memory_free
          - entity: sensor.memory_use_percent
          - entity: sensor.swap_free
          - entity: sensor.swap_use_percent
          - entity: sensor.cpu_temperature
          - entity: sensor.processor_use
          - entity: sensor.load_5m
          - entity: sensor.disk_free_home
          - entity: sensor.network_in_enxb827ebcca772
          - entity: sensor.network_out_enxb827ebcca772
          - entity: sensor.network_in_wlan0
          - entity: sensor.network_out_wlan0
          - entity: sensor.disk_use_percent_home
          - entity: sensor.home_assistant_v2_db
      - type: 'custom:mini-graph-card'
        name: 'CPU Temp, Disk and Memory Use'
        entities:
          - sensor.memory_use_percent
          - sensor.disk_use_percent_home
          - sensor.cpu_temperature
      - type: 'custom:mini-graph-card'
        name: Processor and Swap use
        entities:
          - sensor.processor_use
          - sensor.swap_use_percent
      - type: 'custom:mini-graph-card'
        entities:
          - sensor.load_5m
      - type: 'custom:mini-graph-card'
        name: DB Size
        entities:
          - sensor.home_assistant_v2_db
    badges: []
    path: system
  - title: cameras
    cards:
      - type: picture-entity
        entity: camera.foscam_mjpeg
      - type: picture-entity
        entity: camera.foscam_native
      - type: picture-entity
        entity: camera.android_webcam_mjpeg
      - type: entities
        title: Input boolean
        entities:
          - input_boolean.foscam_preset_1
          - input_boolean.foscam_preset_2
          - input_boolean.foscam_preset_3
          - input_boolean.foscam_preset_4
    badges: []
    path: cameras
  - title: all devices
    cards: []
    badges:
      - device_tracker.qcombtd
      - device_tracker.04d6aaa0ae97
      - device_tracker.34ce00c6f5fc
      - device_tracker.7811dc6a8dd9
      - device_tracker.b827ebcca772
      - device_tracker.galaxy_s8
      - device_tracker.meital_s9
      - device_tracker.f4f5dbd0d909
      - device_tracker.redmi_2
      - device_tracker.30fd380497d1
      - device_tracker.redmi
      - device_tracker.hk_nova
      - device_tracker.acd1b8e5bf3f
      - device_tracker.ipad_gabrielle
      - device_tracker.64a2f95150ee
      - device_tracker.fcc2deac7977
      - device_tracker.9c5cf9588783
      - device_tracker.victurio
      - device_tracker.840d8e489a2a
      - device_tracker.000000020201
      - device_tracker.guy_mac
      - device_tracker.04b167103f40
      - device_tracker.guyplus_one
      - device_tracker.2400bacdd0dd
      - device_tracker.3cbd3e1a3f9d
      - device_tracker.f04f7cff99c9
      - device_tracker.685acfad03a2
      - device_tracker.b827eb99f227
      - device_tracker.24181d2414cd
      - device_tracker.7811dc9eb23c
      - device_tracker.samsung_gear_s2
      - device_tracker.yonis_phone
      - device_tracker.2c598a587acb
      - device_tracker.samsung_s8_bt
      - device_tracker.samsung_gear_s2_bt
      - device_tracker.7802f8ffcdfe
      - device_tracker.c485082bc3ca
      - device_tracker.e8abfa00230c
      - device_tracker.samsung_s8
      - device_tracker.c0eefb24470b
      - device_tracker.24181d041d91
      - device_tracker.meital_galaxy_s9
      - device_tracker.84a466ff2bde
    path: all_devices
  - title: Deluge
    cards:
      - show_header_toggle: true
        type: entities
        title: Deluge Sensors
        entities:
          - entity: sensor.localdeluge_down_speed
          - entity: sensor.localdeluge_up_speed
          - entity: sensor.localdeluge_status
          - entity: switch.localdeluge
          - entity: sensor.remotedeluge_down_speed
          - entity: sensor.remotedeluge_up_speed
          - entity: sensor.remotedeluge_status
          - entity: switch.remotedeluge
    badges: []
    path: deluge
  - title: Media
    cards:
      - type: 'custom:mini-media-player'
        entity: media_player.living_room_tv
      - type: 'custom:mini-media-player'
        entity: media_player.kodi
      - type: 'custom:mini-media-player'
        entity: media_player.googlehome3672
      - type: 'custom:mini-media-player'
        entity: media_player.samsung_tv_remote
      - type: 'custom:mini-media-player'
        entity: media_player.entryway_speaker
      - type: 'custom:mini-media-player'
        entity: media_player.home_group
      - entity: media_player.spotify
        type: 'custom:mini-media-player'
    badges: []
  - title: PiHole
    cards:
      - type: entities
        title: PiHole Entities
        entities:
          - entity: sensor.pi_hole_ads_percentage_blocked_today
          - entity: sensor.pi_hole_ads_blocked_today
          - entity: sensor.pi_hole_domains_blocked
          - entity: sensor.pi_hole_dns_queries_today
          - entity: sensor.pi_hole_dns_unique_clients
    badges: []
    icon: ''
title: Home
resources:
  - type: module
    url: /local/mini-graph-card-bundle.js?v=0.2.4
  - type: module
    url: https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/weather-card/weather-card.min.js
  - type: module
    url: /local/mini-media-player-bundle.js?v=1.0.1

