shell_command:
  foscam_preset1: !secret foscam_preset1
  foscam_preset2: !secret foscam_preset2
  foscam_preset3: !secret foscam_preset3
  foscam_preset4: !secret foscam_preset4

camera:
  - platform: foscam
    ip: !secret foscam_ip
    username: !secret foscam_username
    password: !secret foscam_password
    port: !secret foscam_port
    name: Foscam Native
  - platform: mjpeg
    mjpeg_url: !secret foscam_url
    name: Foscam MJPEG
  - platform: mjpeg
    mjpeg_url: !secret mjpeg_url
    name: Android Webcam MJPEG
    username: !secret webcam_username
    password: !secret webcam_password

input_boolean:
  foscam_preset_1:
    name: Foscam Preset 1
    initial: on
  foscam_preset_2:
    name: Foscam Preset 2
    initial: on
  foscam_preset_3:
    name: Foscam Preset 3
    initial: on
  foscam_preset_4:
    name: Foscam Preset 4
    initial: on

# AUTOMATIONS:
automation:
- alias: foscam_preset_1
  trigger:
    platform: state
    entity_id: input_boolean.foscam_preset_1
  action:
    service: shell_command.foscam_preset1
  id: 9f2099c4b39745118efc5602a24c03c0
- alias: foscam_preset_2
  trigger:
    platform: state
    entity_id: input_boolean.foscam_preset_2
  action:
    service: shell_command.foscam_preset2
  id: 4a461cd975174886a1a744d0b6c66196
- alias: foscam_preset_3
  trigger:
    platform: state
    entity_id: input_boolean.foscam_preset_3
  action:
    service: shell_command.foscam_preset3
  id: d9160f749dce49c1be85f9a9371da63f
- alias: foscam_preset_4
  trigger:
    platform: state
    entity_id: input_boolean.foscam_preset_4
  action:
    service: shell_command.foscam_preset4
  id: 5e4ec1dd013a4f4a9cf82c9fafc30db4
