sensor:
  - platform: template
    sensors:
      guy_presence:
        friendly_name: 'Guy Presence'
        value_template: '{% if is_state("device_tracker.samsung_s8", "home") or is_state("device_tracker.samsung_s8_bt"  or is_state("device_tracker.samsung_gear_s2", "home" )  or is_state("device_tracker.samsung_gear_s2_bt", "home" ), "home" ) %}home{% else %}away{% endif %}'
        entity_picture_template: /local/guy.jpg
      meital_presence:
        friendly_name: 'Meital Presence'
        value_template: '{% if is_state(" device_tracker.meital_galaxy_s9", "home") or is_state("device_tracker.meital_s9", "home" ) %}home{% else %}away{% endif %}'
        entity_picture_template: /local/meital.jpg
      occupancy_status:
        friendly_name: 'Master Presence'
        value_template: '{% if is_state("sensor.guy_presence", "home") or is_state("sensor.meital_presence", "home" ) %}home{% else %}away{% endif %}'