

sensor:
  - platform: sonarr
    api_key: !secret sonarr_key
    host: !secret sonarr_ip
    port: !secret sonarr_port

  # ################################################################### #
  #               --- Sonarr Upcoming Media --                          #
  # https://github.com/custom-components/sensor.sonarr_upcoming_media   #
  # ################################################################### #
  - platform: sonarr_upcoming_media
    api_key: !secret sonarr_key
    host: !secret sonarr_ip
    port: !secret sonarr_port
    days: 2
    ssl: false
    max: 10