sensor:
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /home
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: memory_use_percent
      - type: swap_use_percent
      - type: swap_free
      - type: load_5m
      - type: processor_use
      - type: last_boot
      - type: network_in
        arg: enxb827ebcca772
      - type: network_out
        arg: enxb827ebcca772
      - type: network_in
        arg: wlan0
      - type: network_out
        arg: wlan0
  - platform: filesize
    file_paths:
      - !secret db_path
  - platform: time_date
    display_options:
      -  'time'
      -  'date'
  - platform: version
    name: HA Installed Version
    scan_interval: 86400
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'    

binary_sensor:
  - platform: template
    sensors:
      cpu_overload:
        value_template: "{{ states('sensor.cpu_use')|int > 25 }}"
        friendly_name: 'cpu above 25 %'