###############################################################################
#   @author         :   Trent Stanton
#   @date           :   19/05/2018
#   @package        :   Xiaomi Robot Vacuum
#   @description    :   Xiaomi Robot Vacuum Control, Zones and Schedule
#   @url            :   https://github.com/stanvx/Home-Assistant-Configuration/blob/master/packages/xiaomi_robot_vacuum.yaml
###############################################################################
homeassistant:
  customize:
    input_boolean.disable_daily_vacuum:
      icon: mdi:stop-circle-outline
    input_boolean.disable_dustbin_notification:
      icon: mdi:delete-empty
    binary_sensor.vacuum_room:
      custom_ui_state_card: state-card-floorplan
      config: !include ../floorplan_vacuum.yaml

binary_sensor:
  - platform: mqtt
    state_topic: dummy/floorplan/sensor
    name: Vacuum Room

frontend:
  extra_html_url:
    - /local/custom_ui/state-card-floorplan.html

group:
  Robot Vacuum:
    control: hidden
    entities:
      - vacuum.xiaomi_vacuum_cleaner
      - input_boolean.disable_daily_vacuum
  Vacuum a Room:
    control: hidden
    entities:
      - input_select.vacuum_room
      - binary_sensor.vacuum_room

vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token

input_boolean:
  daily_vacuum_first_run:
    name: Daily Vacuum First Run
    initial: off
  disable_daily_vacuum:
    name: Disable Daily Vacuum Automation
    initial: on
  disable_dustbin_notification:
    name: Disable Dustbin Notification
    initial: off

input_select:
  vacuum_room:
    name: Choose a room to clean
    options:
      - Select Input
      - All Except Bedroom and Ensuite
      - Bedroom
      - Entryway
      - Kitchen
      - Living Room
      - Mopping Surfaces
      - Balcony
      - Study

script:
  vacuum_bedroom:
        alias: "Vacuum Bedroom"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[25235,26127,28585,30677,1]]
# Entryway not working correctly
  vacuum_entryway:
        alias: "Vacuum Entryway"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[29433,27008,32783,28208,1],[28832,23569,30982,27069,1],[25277,23950,28877,26050,1]]
  vacuum_kitchen:
        alias: "Vacuum Kitchen"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[31365,27277,33015,32227,1]]
  vacuum_living_room:
        alias: "Vacuum Living Room"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[25323,20489,27623,25939,1]]
  vacuum_balcony:
        alias: "Vacuum Balcony"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[25300,18635,30600,20635,1]]
  vacuum_study:
        alias: "Vacuum Study"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[29422,20624,33272,23674,1]]
              
sensor:
  - platform: template
    sensors:
      xiaomi_vacuum_cleaner_status: 
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        friendly_name: "Xiaomi Vacuum Cleaner Status"
        value_template: "{{ states.vacuum.xiaomi_vacuum_cleaner }}"
      xiaomi_vacuum_ip:
        value_template: !secret xiaomi_vacuum_ip
      vacuum_start_time_weekdays:
        friendly_name: 'Start Time (weekdays)'
        value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.vacuum_start_hour_weekdays") | int, states("input_number.vacuum_start_minutes_weekdays") | int) }}'
        entity_id: input_number.vacuum_start_hour_weekdays
      vacuum_start_time_weekend:
        friendly_name: 'Start Time (weekend)'
        value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.vacuum_start_hour_weekend") | int, states("input_number.vacuum_start_minutes_weekend") | int) }}'
        entity_id: input_number.vacuum_start_hour_weekend
      vacuum_status:
        friendly_name: "Vacuum - State"
        value_template: "State: {{ states.vacuum.xiaomi_vacuum.attributes.status }}"
        entity_id: vacuum.xiaomi_vacuum
      vacuum_weekdays:
        friendly_name: "Vacuum - Weekdays"
        value_template: ""
      vacuum_weekend:
        friendly_name: "Vacuum - Weekend"
        value_template: ""
      vacuum_battery:
        friendly_name: "Vacuum - Battery"
        value_template: "Battery: {{ states.vacuum.xiaomi_vacuum.attributes.battery_level | float | int }}"
        icon_template: '{{ states.vacuum.xiaomi_vacuum.attributes.battery_icon }}'
        device_class: battery
        unit_of_measurement: '%'
        entity_id: vacuum.xiaomi_vacuum
      vacuum_accessories:
        friendly_name: "Vacuum - Consumption"
        value_template: "Consumption"
      vacuum_operation:
        friendly_name: "Vacuum - Operations"
        value_template: "Operations"
      vacuum_main_brush:
        friendly_name: "Vacuum - Main Brush"
        value_template: "Main Brush: {{ states.vacuum.xiaomi_vacuum.attributes.main_brush_left }} h"
        entity_id: vacuum.xiaomi_vacuum
      vacuum_side_brush:
        friendly_name: "Vacuum - Side Brush"
        value_template: "Side Brush: {{ states.vacuum.xiaomi_vacuum.attributes.side_brush_left }} h"
        entity_id: vacuum.xiaomi_vacuum
      vacuum_filter:
        friendly_name: "Vacuum - Filter"
        value_template: "Filter: {{ states.vacuum.xiaomi_vacuum.attributes.filter_left }} h"
        entity_id: vacuum.xiaomi_vacuum
      vacuum_sensor:
        friendly_name: "Vacuum - Drawer"
        value_template: "Drawer: {{ states.vacuum.xiaomi_vacuum.attributes.sensor_dirty_left }} h"
        entity_id: vacuum.xiaomi_vacuum
      vacuum_fan_speed:
        friendly_name: "Vacuum - Power"
        value_template: "Power: {{ states.vacuum.xiaomi_vacuum.attributes.fan_speed }}"
        entity_id: vacuum.xiaomi_vacuum
      vacuum_cleaning_time:
        friendly_name: "Cleaning - Time"
        value_template: "Cleaning Time: {{ states.vacuum.xiaomi_vacuum.attributes.cleaning_time }}"
        entity_id: vacuum.xiaomi_vacuum
      vacuum_cleaned_area:
        friendly_name: Cleaned Area
        unit_of_measurement: 'm ²'
        value_template: "Cleaned - Area {{ states.vacuum.xiaomi_vacuum.attributes.cleaned_area }}"
        entity_id: vacuum.xiaomi_vacuum        
      vacuum_fan_speed_list:
        friendly_name: "Vacuum - Fan Speed List"
        value_template: "{{ states.vacuum.xiaomi_vacuum.attributes.fan_speed_list }}"
        entity_id: vacuum.xiaomi_vacuum

###############################################################################
#                               Automations
###############################################################################
automation:
  # - alias: Start Daily Vacuum
  #   trigger:
  #   - platform: state
  #     entity_id: group.family
  #     from: 'home'
  #     to: 'not_home'
  #     for:
  #       minutes: 2
  #   - platform: time
  #     at: '7:02:00'
  #   condition:
  #     condition: and
  #     conditions:
  #     - condition: state
  #       entity_id: input_boolean.daily_vacuum_first_run
  #       state: 'off'
  #     - condition: time
  #       after: '07:00:00'
  #       before: '22:00:00'
  #     - condition: state
  #       entity_id: group.family
  #       state: 'not_home'
  #     - condition: state
  #       entity_id: input_boolean.disable_daily_vacuum
  #       state: 'off'
  #   action:
  #   - delay: '00:00:30'
  #   - service: vacuum.turn_on
  #     entity_id: vacuum.xiaomi_vacuum_cleaner
  #   - service: homeassistant.turn_on
  #     entity_id: input_boolean.daily_vacuum_first_run

  # - alias: Reset Daily Vacuum First Run state at midnight
  #   trigger:
  #   - platform: time
  #     at: '0:00:00'
  #   action:
  #   - service: homeassistant.turn_off
  #     entity_id: input_boolean.daily_vacuum_first_run

  # - alias: Send alert after daily vacuum to empty the dustbin
  #   trigger:
  #   - platform: state
  #     entity_id: group.family
  #     to: 'home'
  #     for:
  #       minutes: 2
  #   condition:
  #     condition: and
  #     conditions:
  #     - condition: state
  #       entity_id: input_boolean.daily_vacuum_first_run
  #       state: 'on'
  #     - condition: time
  #       after: '08:30:00'
  #       before: '22:30:00'
  #     - condition: template
  #       value_template: >
  #         {% if states.automation.send_alert_after_daily_vacuum_to_empty_the_dustbin.last_triggered is not none %}
  #           {% if as_timestamp(now()) | int   -  as_timestamp(states.automation.send_alert_after_daily_vacuum_to_empty_the_dustbin.attributes.last_triggered) | int > 1800 %} true {% else %} false
  #           {% endif %}
  #         {% else %}
  #         false
  #         {% endif %}
  #     - condition: state
  #       entity_id: input_boolean.disable_dustbin_notification
  #       state: 'off'
  #   action:
  #     - service: script.speech_processing
  #       data_template:
  #         speech_message: >
  #          {% if (is_state('device_tracker.google_maps_109209758211303121867', 'home')) or (is_state('device_tracker.rachels_iphone', 'home'))  %}
  #            Attention!: the vacuum dustbin needs to be cleared.
  #          {% endif %}
  #     - service_template: >
  #         {% if (is_state('device_tracker.google_maps_109209758211303121867', 'home')) and (is_state('device_tracker.rachels_iphone', 'home'))  %}
  #           notify.trent_and_rachel
  #         {% elif is_state('device_tracker.google_maps_109209758211303121867', 'home') %}
  #           notify.trent
  #         {% elif is_state('device_tracker.rachels_iphone', 'home') %}
  #           notify.rachel
  #         {% endif %}
  #       data:
  #         message: 'Hey, the vacuum dustbin needs to be cleared'
  #         title: 'Vacuum Dustbin'

  - alias: Start Cleaning Room
    hide_entity: True
    trigger:
    - platform: state
      entity_id: input_select.vacuum_room
      from: 'Select Input'
    action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% elif is_state("input_select.vacuum_room", "Bedroom") %}
            script.vacuum_bedroom
          {% elif is_state("input_select.vacuum_room", "Entryway") %}
            script.vacuum_entryway
          {% elif is_state("input_select.vacuum_room", "Kitchen") %}
            script.vacuum_kitchen
          {% elif is_state("input_select.vacuum_room", "Living Room") %}
            script.vacuum_living_room
          {% elif is_state("input_select.vacuum_room", "Balcony") %}
            script.vacuum_balcony
          {% elif is_state("input_select.vacuum_room", "Study") %}
            script.vacuum_study
          {% else %}
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.vacuum_room
      data_template:
        option: "Select Input"
