###############################################################################
#   @author         :   Trent Stanton
#   @date           :   19/05/2018
#   @package        :   Xiaomi Robot Vacuum
#   @description    :   Xiaomi Robot Vacuum Control, Zones and Schedule
#   @url            :   https://github.com/stanvx/Home-Assistant-Configuration/blob/master/packages/xiaomi_robot_vacuum.yaml
###############################################################################
homeassistant:
  customize:
    input_boolean.disable_daily_vacuum:
      icon: mdi:stop-circle-outline
    input_boolean.disable_dustbin_notification:
      icon: mdi:delete-empty
    binary_sensor.vacuum_room:
      custom_ui_state_card: state-card-floorplan
      config: !include ../floorplan_vacuum.yaml

# binary_sensor:
#   - platform: mqtt
#     state_topic: dummy/floorplan/sensor
#     name: Vacuum Room

# frontend:
#   extra_html_url:
#     - /local/custom_ui/state-card-floorplan.html

group:
  Robot Vacuum:
    control: hidden
    entities:
      - vacuum.xiaomi_vacuum_cleaner
#      - input_boolean.disable_daily_vacuum
  Vacuum a Room:
    control: hidden
    entities:
      - input_select.vacuum_room
      - binary_sensor.vacuum_room

vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token

#input_boolean:
#  daily_vacuum_first_run:
#    name: Daily Vacuum First Run
#    initial: off
#  disable_daily_vacuum:
#    name: Disable Daily Vacuum Automation
#    initial: on
#  disable_dustbin_notification:
#    name: Disable Dustbin Notification
#    initial: off

input_select:
  vacuum_room:
    name: Choose a room to clean
    options:
      - Select Input
      - All Except Bedroom and Ensuite
      - Bedroom
      - Entryway
      - Kitchen
      - Living Room
      - Mopping Surfaces
      - Balcony
      - Study

script:
  vacuum_all_except_bedroom_and_ensuite:
        alias: "Vacuum All Except Bedroom and Ensuite"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[16034,19737,26234,29237,1],[19487,29248,26237,32198,1]]
  vacuum_bedroom:
        alias: "Vacuum Bedroom"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[26114,22606,30814,26006,1]]
# Entryway not working correctly
  vacuum_entryway:
        alias: "Vacuum Entryway"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[23613,20044,26013,25944,1], [23733,20049,27083,22399,1]]
  vacuum_kitchen:
        alias: "Vacuum Kitchen"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[27167,18145,32367,21795,1]]
  vacuum_living_room:
        alias: "Vacuum Living Room"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[20524,23178,25924,25828,1]]
  vacuum_mopping_surfaces:
        alias: "Vacuum Mopping Surfaces"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[16602,29163,22052,32313,1],[16028,24951,21578,28151,1],[22975,22737,24375,25087,1]]
  vacuum_balcony:
        alias: "Vacuum Balcony"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[18841,20486,20841,25786,1]]
  vacuum_study:
        alias: "Vacuum Study"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[20984,17553,23534,21703,1]]
sensor:
  - platform: template
    sensors:
      xiaomi_vacuum_cleaner_status:
        friendly_name: "Xiaomi Vacuum Cleaner Status"
        value_template: "{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}"

###############################################################################
#                               Automations
###############################################################################
automation:
  # - alias: Start Daily Vacuum
  #   trigger:
  #   - platform: state
  #     entity_id: group.family
  #     from: 'home'
  #     to: 'not_home'
  #     for:
  #       minutes: 2
  #   - platform: time
  #     at: '7:02:00'
  #   condition:
  #     condition: and
  #     conditions:
  #     - condition: state
  #       entity_id: input_boolean.daily_vacuum_first_run
  #       state: 'off'
  #     - condition: time
  #       after: '07:00:00'
  #       before: '22:00:00'
  #     - condition: state
  #       entity_id: group.family
  #       state: 'not_home'
  #     - condition: state
  #       entity_id: input_boolean.disable_daily_vacuum
  #       state: 'off'
  #   action:
  #   - delay: '00:00:30'
  #   - service: vacuum.turn_on
  #     entity_id: vacuum.xiaomi_vacuum_cleaner
  #   - service: homeassistant.turn_on
  #     entity_id: input_boolean.daily_vacuum_first_run

  # - alias: Reset Daily Vacuum First Run state at midnight
  #   trigger:
  #   - platform: time
  #     at: '0:00:00'
  #   action:
  #   - service: homeassistant.turn_off
  #     entity_id: input_boolean.daily_vacuum_first_run

  # - alias: Send alert after daily vacuum to empty the dustbin
  #   trigger:
  #   - platform: state
  #     entity_id: group.family
  #     to: 'home'
  #     for:
  #       minutes: 2
  #   condition:
  #     condition: and
  #     conditions:
  #     - condition: state
  #       entity_id: input_boolean.daily_vacuum_first_run
  #       state: 'on'
  #     - condition: time
  #       after: '08:30:00'
  #       before: '22:30:00'
  #     - condition: template
  #       value_template: >
  #         {% if states.automation.send_alert_after_daily_vacuum_to_empty_the_dustbin.last_triggered is not none %}
  #           {% if as_timestamp(now()) | int   -  as_timestamp(states.automation.send_alert_after_daily_vacuum_to_empty_the_dustbin.attributes.last_triggered) | int > 1800 %} true {% else %} false
  #           {% endif %}
  #         {% else %}
  #         false
  #         {% endif %}
  #     - condition: state
  #       entity_id: input_boolean.disable_dustbin_notification
  #       state: 'off'
  #   action:
  #     - service: script.speech_processing
  #       data_template:
  #         speech_message: >
  #          {% if (is_state('device_tracker.google_maps_109209758211303121867', 'home')) or (is_state('device_tracker.rachels_iphone', 'home'))  %}
  #            Attention!: the vacuum dustbin needs to be cleared.
  #          {% endif %}
  #     - service_template: >
  #         {% if (is_state('device_tracker.google_maps_109209758211303121867', 'home')) and (is_state('device_tracker.rachels_iphone', 'home'))  %}
  #           notify.trent_and_rachel
  #         {% elif is_state('device_tracker.google_maps_109209758211303121867', 'home') %}
  #           notify.trent
  #         {% elif is_state('device_tracker.rachels_iphone', 'home') %}
  #           notify.rachel
  #         {% endif %}
  #       data:
  #         message: 'Hey, the vacuum dustbin needs to be cleared'
  #         title: 'Vacuum Dustbin'

  - alias: Start Cleaning Room
    hide_entity: True
    trigger:
    - platform: state
      entity_id: input_select.vacuum_room
      from: 'Select Input'
    action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.vacuum_room", "All Except Bedroom and Ensuite") %}
            script.vacuum_all_except_bedroom_and_ensuite
          {% elif is_state("input_select.vacuum_room", "Bedroom") %}
            script.vacuum_bedroom
          {% elif is_state("input_select.vacuum_room", "Entryway") %}
            script.vacuum_entryway
          {% elif is_state("input_select.vacuum_room", "Kitchen") %}
            script.vacuum_kitchen
          {% elif is_state("input_select.vacuum_room", "Living Room") %}
            script.vacuum_living_room
          {% elif is_state("input_select.vacuum_room", "Mopping Surfaces") %}
            script.vacuum_mopping_surfaces
          {% elif is_state("input_select.vacuum_room", "Balcony") %}
            script.vacuum_balcony
          {% elif is_state("input_select.vacuum_room", "Study") %}
            script.vacuum_study
          {% else %}
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.vacuum_room
      data_template:
        option: "Select Input"
